name = "AutomaticProofGeneralization"
version = "0.1.0"
defaultTargets = ["webdemo"]

[[lean_lib]]
name = "AutomaticProofGeneralization"

[[lean_lib]]
name = "WebDemo"
leanOptions = { pp.showLetValues = false }
moreServerOptions = { pp.showLetValues = false }


[[require]]
name = "verso"
scope = "leanprover"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_exe]]
name = "webdemo"
srcDir = "WebDemo"
root = "Main"
supportInterpreter = true