name = "AutomaticProofGeneralization"
version = "0.1.0"
defaultTargets = ["webdemo"]

[[lean_lib]]
name = "AutomaticProofGeneralization"

[[lean_lib]]
name = "WebDemo"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.18.0-rc1"

[[require]]
name = "verso"
scope = "leanprover"
rev = "v4.18.0-rc1"

[[lean_exe]]
name = "webdemo"
srcDir = "WebDemo"
root = "Main"
supportInterpreter = true